
import caps.main.Caps;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author angel
 */
public class ControlPointCap extends javax.swing.JFrame {

    String silueta;
    int pos;
    int cuenta;
    double cuentaOP;
    double cambioOP;
    String prueba;
    String talla;
    String modelo;
    int precio;
    int contCaps;

    Caps[] caps = new Caps[10];
    
    /**
     * Creates new form ControlPointCap
     */
    public ControlPointCap() {
        
        initComponents();
        setColorButtons();
        inicializar();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        B9Tw = new javax.swing.JButton();
        B59 = new javax.swing.JButton();
        B39 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B9F = new javax.swing.JButton();
        B59Flp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAInfo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFTalla = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SPrecio = new javax.swing.JSpinner();
        TFModelo1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LCambio = new javax.swing.JTextField();
        BNuevo = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();
        BCuenta = new javax.swing.JButton();
        BAnadirCap = new javax.swing.JButton();
        TFTotal = new javax.swing.JTextField();
        LMontoRecibido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BCambio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B9Tw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9twe.png"))); // NOI18N
        B9Tw.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "9 Twenty", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        B9Tw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9TwActionPerformed(evt);
            }
        });
        jPanel1.add(B9Tw, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 90, 80));

        B59.setForeground(new java.awt.Color(153, 51, 0));
        B59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/59.png"))); // NOI18N
        B59.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "59 Fifty", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        B59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B59ActionPerformed(evt);
            }
        });
        jPanel1.add(B59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 80));

        B39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/39 (1).png"))); // NOI18N
        B39.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "39 Thirty", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        B39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B39ActionPerformed(evt);
            }
        });
        jPanel1.add(B39, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, 80));

        B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9.png"))); // NOI18N
        B9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "9 Forty", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        jPanel1.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 80));

        B9F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9fifty.png"))); // NOI18N
        B9F.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "9 Fifty", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        B9F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9FActionPerformed(evt);
            }
        });
        jPanel1.add(B9F, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 90, 70));

        B59Flp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/59lp.png"))); // NOI18N
        B59Flp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "59 Fifty lp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        B59Flp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B59FlpActionPerformed(evt);
            }
        });
        jPanel1.add(B59Flp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 80));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Siluetas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/capicon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 80));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("The     King      Cap");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 480, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TAInfo.setColumns(20);
        TAInfo.setRows(5);
        jScrollPane1.setViewportView(TAInfo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 550, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Talla");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Modelo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 90, 20));

        TFTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTallaActionPerformed(evt);
            }
        });
        jPanel2.add(TFTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Precio");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 90, -1));
        jPanel2.add(SPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 130, 30));

        TFModelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFModelo1ActionPerformed(evt);
            }
        });
        jPanel2.add(TFModelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 170, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 560, 290));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tu cambio es");

        LCambio.setEditable(false);
        LCambio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LCambioActionPerformed(evt);
            }
        });

        BNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-archivo.png"))); // NOI18N
        BNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });

        BCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        BCancelar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cancelar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });

        BCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/simbolo-de-dolar.png"))); // NOI18N
        BCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuenta\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        BCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCuentaActionPerformed(evt);
            }
        });

        BAnadirCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        BAnadirCap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir cap", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        BAnadirCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnadirCapActionPerformed(evt);
            }
        });

        TFTotal.setEditable(false);
        TFTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        TFTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTotalActionPerformed(evt);
            }
        });

        LMontoRecibido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LMontoRecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LMontoRecibidoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Monto Recibido");

        BCambio.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        BCambio.setText("Cambio");
        BCambio.setBorder(null);
        BCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LCambio)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LMontoRecibido)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(BCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BAnadirCap, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BAnadirCap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(BCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFTotal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LMontoRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(BCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 770, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B9TwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9TwActionPerformed
        silueta = "9 Twenty";
        B9Tw.setBackground(Color.GRAY);
        B59Flp.setBackground(Color.WHITE);
        B9F.setBackground(Color.WHITE);
        B9.setBackground(Color.WHITE);
        B39.setBackground(Color.WHITE);
        B59.setBackground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_B9TwActionPerformed

    private void B59FlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B59FlpActionPerformed
        silueta = "59 Fifty LP";
        B9Tw.setBackground(Color.WHITE);
        B59Flp.setBackground(Color.GRAY);
        B9F.setBackground(Color.WHITE);
        B9.setBackground(Color.WHITE);
        B39.setBackground(Color.WHITE);
        B59.setBackground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_B59FlpActionPerformed

    private void TFTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTallaActionPerformed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        pos = 0;
        cuenta = 0;
        inicializar();
        TAInfo.setText("");
        clearElements();
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCuentaActionPerformed
        for (Caps cap : caps) {
            if (cap.getPrecio() != 0 && cap.getSilueta() != null) {
                cuenta += cap.getPrecio();
            }
        }
        
        TFTotal.setText(String.valueOf(cuenta));
        cuentaOP = cuenta;
        cuenta = 0;
    }//GEN-LAST:event_BCuentaActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        for (int i = caps.length-1; i > 0; i--) {
            if(caps[i].getModelo()!=null){
                caps[i] = new Caps();
                break;
            }
        }
        mostrarDatos();
    }//GEN-LAST:event_BCancelarActionPerformed

    private void TFTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTotalActionPerformed

    private void LCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LCambioActionPerformed

    private void BAnadirCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnadirCapActionPerformed
        talla = TFTalla.getText();
        modelo = TFModelo1.getText();
       precio = (int)SPrecio.getValue();
        
        if ((silueta != null) && !(talla.isBlank()) && !(modelo.isBlank()) && precio>0) {
            if(contCaps<10){
                caps[pos++] = new Caps(silueta, talla, modelo, precio);
                clearElements();
                mostrarDatos();
                contCaps++;
            }else{
                JOptionPane.showMessageDialog(null, "Excediste el numero de productos");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctos solicitados");
            
        }


    }//GEN-LAST:event_BAnadirCapActionPerformed

    private void B59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B59ActionPerformed
        silueta = "9 Fifty";
        B59.setBackground(Color.GRAY);
        B9Tw.setBackground(Color.WHITE);
        B59Flp.setBackground(Color.WHITE);
        B9F.setBackground(Color.WHITE);
        B9.setBackground(Color.WHITE);
        B39.setBackground(Color.WHITE);

    }//GEN-LAST:event_B59ActionPerformed

    private void B39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B39ActionPerformed
        silueta = "39 Thirty";
        B9Tw.setBackground(Color.WHITE);
        B59Flp.setBackground(Color.WHITE);
        B9F.setBackground(Color.WHITE);
        B9.setBackground(Color.WHITE);
        B39.setBackground(Color.GRAY);
        B59.setBackground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_B39ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        silueta = "9 Forty";
        B9Tw.setBackground(Color.WHITE);
        B59Flp.setBackground(Color.WHITE);
        B9F.setBackground(Color.WHITE);
        B9.setBackground(Color.GRAY);
        B39.setBackground(Color.WHITE);
        B59.setBackground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_B9ActionPerformed

    private void B9FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9FActionPerformed
        silueta = "9 Fifty";
        B9Tw.setBackground(Color.WHITE);
        B59Flp.setBackground(Color.WHITE);
        B9F.setBackground(Color.GRAY);
        B9.setBackground(Color.WHITE);
        B39.setBackground(Color.WHITE);
        B59.setBackground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_B9FActionPerformed

    private void LMontoRecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LMontoRecibidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LMontoRecibidoActionPerformed

    private void BCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCambioActionPerformed

     prueba = LMontoRecibido.getText();
        
    
        
    if (!prueba.isEmpty()&&(!prueba.matches(".*[a-zA-Z].*"))){
        cambioOP = Double.parseDouble(prueba);
        if(cambioOP>=cuentaOP && cuentaOP!=0){
            cambioOP -= cuentaOP;
            LCambio.setText(String.valueOf(String.format("%.2f", cambioOP)));
        }else {
            JOptionPane.showMessageDialog(null, "Ingresa una cantidad igual o mayor a la cuenta");
            LMontoRecibido.setText("");
        }
    }else{
        JOptionPane.showMessageDialog(null, "Ingresa el monto recibido");
        LMontoRecibido.setText("");
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_BCambioActionPerformed

    private void TFModelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFModelo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFModelo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPointCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPointCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPointCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPointCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPointCap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B39;
    private javax.swing.JButton B59;
    private javax.swing.JButton B59Flp;
    private javax.swing.JButton B9;
    private javax.swing.JButton B9F;
    private javax.swing.JButton B9Tw;
    private javax.swing.JButton BAnadirCap;
    private javax.swing.JButton BCambio;
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BCuenta;
    private javax.swing.JButton BNuevo;
    private javax.swing.JTextField LCambio;
    private javax.swing.JTextField LMontoRecibido;
    private javax.swing.JSpinner SPrecio;
    private javax.swing.JTextArea TAInfo;
    private javax.swing.JTextField TFModelo1;
    private javax.swing.JTextField TFTalla;
    private javax.swing.JTextField TFTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setColorButtons() {
        B9Tw.setBackground(Color.WHITE);
        B59Flp.setBackground(Color.WHITE);
        B9F.setBackground(Color.WHITE);
        B9.setBackground(Color.WHITE);
        B39.setBackground(Color.WHITE);
        B59.setBackground(Color.WHITE);
    }

    private void inicializar() {
        for (int i = 0; i < caps.length; i++) {
            caps[i] = new Caps();
        }
    }

    private void mostrarDatos() {
        TAInfo.setText("");
        for (Caps cp : caps) {
            if (cp.getSilueta() != null) {
                TAInfo.append(cp.toString() + "\n");
            }

        }
    }
    
   private void clearElements(){
        B9Tw.setBackground(Color.WHITE);
        B59Flp.setBackground(Color.WHITE);
        B9F.setBackground(Color.WHITE);
        B9.setBackground(Color.WHITE);
        B39.setBackground(Color.WHITE);
        B59.setBackground(Color.WHITE);
        silueta = null;
        TFModelo1.setText("");
        TFTalla.setText("");
        SPrecio.setValue(0);
        LMontoRecibido.setText("");
        LCambio.setText("");
        TFTotal.setText("");
   }

}
